---
prometheus:
  scrapeAnnotations: true
  serviceAccount: "monitoring-prometheus-kube-prometheus"
  namespace: monitoring
  podMonitor:
    enabled: false
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: true
speaker:
  tolerations:
    - key: dedicated
      operator: Equal
      value: gpu
      effect: NoExecute
controller:
  tolerations:
    - key: dedicated
      operator: Equal
      value: gpu
      effect: NoExecute
