---
- name: letsencrypt group on turnserver
  ansible.builtin.user:
    name: turnserver
    groups:
      - letsencrypt
    system: true
    append: true
- name: Include raypappa.coturn
  ansible.builtin.import_role:
    name: raypappa.coturn
- name: Restart coturn
  ansible.builtin.systemd_service:
    name: coturn
    state: started
