---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-tunnel-credentials
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-tunnel-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: iqot67fv4b3jab62rt6dsikp4m/credentials.json
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-cnpg-db
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-db-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DB_HOSTNAME: "faerun-cnpg-001-rw.database.svc"
        DB_PORT: "5432"
        DB_DATABASE_NAME: "immich"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: izgrqebrzrkusffs2l4gvqxkdu/password
    - secretKey: username
      remoteRef:
        key: izgrqebrzrkusffs2l4gvqxkdu/username
