---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spotizerr-admin
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: spotizerr-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: wwgjphpjy2jgu6ar7ryce6xnwu/password
    - secretKey: username
      remoteRef:
        key: wwgjphpjy2jgu6ar7ryce6xnwu/username
