#SPDX-License-Identifier: MIT-0
---
# handlers file for livekit
- name: Systemctl reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Validate Nginx config
  ansible.builtin.command:
    cmd: nginx -t
- name: Nginx reload
  ansible.builtin.command:
    cmd: nginx -s reload
