---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: k3s_agent | Apply node taints via Kubernetes API
  kubernetes.core.k8s_taint:
    state: present
    name: "{{ ansible_hostname }}"
    taints: "{{ k3s_agent_node_taints }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  delegate_to: "{{ k3s_controlplane_singleton_host }}"
  when: k3s_agent_node_taints is defined and k3s_agent_node_taints | length > 0
