---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-auth
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TS_AUTHKEY: "{{ .authkey }}"
  data:
    - secretKey: authkey
      remoteRef:
        key: 3lzwejpj3p4mdkwqghrhbbm4m4/password
