---
monitoring:
  enabled: true
csi:
  nfs:
    enabled: true
  disableHolderPods: true
  enableCSIHostNetwork: true
  enableVolumeGroupSnapshot: false
  pluginTolerations:
    - key: dedicated
      operator: Equal
      value: gpu
      effect: NoExecute
  provisionerTolerations:
    - key: dedicated
      operator: Equal
      value: gpu
      effect: NoExecute
