# SPDX-License-Identifier: MIT-0
---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Create letsencrypt group
      ansible.builtin.group:
        name: letsencrypt
        state: present
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Create nginx log format
      ansible.builtin.copy:
        dest: /etc/nginx/conf.d/log-format.conf
        content: |
          log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        mode: "0644"
  vars:
    certbot_certs:
      - name: test.example.com
    livekit_config:
      port: 7880
      bind_addresses:
        - ""
      rtc:
        tcp_port: 7881
        port_range_start: 50000
        port_range_end: 60000
        use_external_ip: false
        enable_loopback_candidate: false
      redis:
        address: localhost:6379
        username: ""
        password: ""
        db: 0
        use_tls: false
        sentinel_master_name: ""
        sentinel_username: ""
        sentinel_password: ""
        sentinel_addresses: []
        cluster_addresses: []
        max_redirects: null
      turn:
        enabled: false
        domain: livekit.example.com
        cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
        key_file: /etc/ssl/private/ssl-cert-snakeoil.key
      keys:
        devkey: secret
  roles:
    - role: livekit
