---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/requirements.json
roles:
  - name: xolyu.mariadb
    version: "0.2.0"
  - name: hussainweb.chezmoi
    version: main
  - src: https://github.com/raypappa/ansible-role-coturn.git
    name: raypappa.coturn
    version: "main"
  - name: geerlingguy.certbot
    version: 5.4.1
  - name: nginxinc.nginx
    src: https://github.com/nginx/ansible-role-nginx.git
    # renovate: datasource=git-refs packageName=https://github.com/nginx/ansible-role-nginx.git currentValue=main
    version: 5271d0c6b23f81bbbebed427b460330b2d04158f
  - name: nginxinc.nginx_config
    src: https://github.com/nginx/ansible-role-nginx-config.git
    # renovate: datasource=git-refs packageName=https://github.com/nginx/ansible-role-nginx-config.git currentValue=main
    version: 2df21603d958a6171c7a7d5d274cfc5e84f85a05
collections:
  - name: community.general
    version: "10.7.0"
  - name: https://github.com/stoneydavis/ansible-collection-pterodactyl.git
    type: git
  - name: community.docker
    version: "4.5.2"
  - name: artis3n.tailscale
    version: "1.0.1"
  - name: community.crypto
    version: "3.0.4"
  - name: ttafsir.sqlite_utils
    version: "1.4.0"
  - name: https://github.com/raypappa/ansible-role-valkey.git
    version: "master"
    type: git
  - name: ansible.posix
    version: 2.0.0
