---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tube-archivist-svc-credentials
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tube-archivist-svc-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: 246mr7lymdaj5fyjiataj3cgzu/username
    - secretKey: password
      remoteRef:
        key: 246mr7lymdaj5fyjiataj3cgzu/password
