---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 9.3.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: elasticsearch
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
            - name: elastic-internal-init-filesystem
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
            - name: elastic-internal-suspend
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
