---
- name: Install lk-jwt-service
  ansible.builtin.get_url:
    url: https://github.com/element-hq/lk-jwt-service/releases/latest/download/lk-jwt-service_linux_amd64
    dest: /usr/local/bin/livekit-jwt
    owner: "{{ livekit_service_user }}"
    group: "{{ livekit_service_user }}"
    mode: "0755"
  register: livekit_jwt_downloaded
- name: Install service for lk-jwt-service
  ansible.builtin.template:
    src: livekit-jwt.service
    dest: /etc/systemd/system/livekit-jwt.service
    owner: root
    group: root
    mode: "0644"
  register: livekit_jwt_service_installed
  notify: Systemctl reload
- name: Restart livekit-jwt
  ansible.builtin.systemd_service:
    name: livekit-jwt
    state: restarted
    daemon_reload: true
  when: livekit_jwt_downloaded.changed or livekit_jwt_service_installed.changed
  register: livekit_jwt_restarted
- name: Enable livekit-jwt
  ansible.builtin.systemd_service:
    name: livekit-jwt
    enabled: true
  when: livekit_jwt_restarted is skipped
  changed_when: false
- name: Install nginx
  ansible.builtin.package:
    name:
      - nginx
- name: Create nginx log format
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/log-format.conf
    content: |
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    mode: "0644"
- name: Disable nginx default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: Configure nginx site
  ansible.builtin.template:
    src: livekit-jwt-nginx.conf
    dest: /etc/nginx/sites-available/livekit-jwt
    owner: root
    group: root
    mode: "0644"
  notify:
    - "Validate Nginx config"
- name: Enable nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/livekit-jwt
    dest: /etc/nginx/sites-enabled/livekit-jwt
    owner: root
    group: root
    mode: "0644"
    state: link
  notify:
    - "Nginx reload"
    - "Validate Nginx config"
- name: Validate nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false
- name: Start nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: started
